### ISSUE TITLE
Regridded cubes have BITPIX = -64 even when input cubes have BITPIX = -32

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/MosaicQueen#10]
This doubles the file size and the memory requirement of mosaicking. I suggest we correct this.

Maybe we cannot force Montage to stick the the input data type, but we could consider converting the regridded FITS to the input FITS type after the fact.

**Comment by gigjozsa** [comment]
You cannot force Montage to output float accuracy cubes, it will only be 64 bit.

But adding the follwowing two lines below
https://github.com/svw26/MosaicSteward/blob/e7cdb4f5dbb30af7cceeabb641691b5a086b40cc/MosaicSteward/make_mosaic.py#L156
should do the trick:
```
g[0].image = g[0].image.astype('>f4')
f[0].image = b[0].image.astype('>f4')
```

**Comment by paoloserra** [comment]
OK @gigjozsa , but then this should be done as part of the changes required to improve our memory usage as part of #9 .
