### ISSUE TITLE
restfreq/restfrq not in mosaic header

### ISSUE THREAD

**Issue by kmhess** [caracal-pipeline/MosaicQueen#18]
I found that fits header keywords associated with the rest frequency and spectroscopic rest frame that were present in the original images and beam files are not transferred to the mosaic file.  I noticed because CARTA was giving me a very strange values for channel velocities in a mosaic.  It might be nice if these are maintained.

**Comment by paoloserra** [comment]
#15 now adds `specsys3`, `restfreq` and `restfrq` in the header (if they are present in the input cubes **before regridding**, since Montage erases all that in the regridded cubes).

@kmhess is there anything else that should be added? Now we're at it...

**Comment by kmhess** [comment]
Other header keywords that may be important to retain if they are present:
SPECSYS (alternative to SPECSYS3)
BUNIT (might be present as a keyword but is blank in the mosaic cubes--at least as I'm looking at the header with CARTA)
VELREF (an alternative used especially by aips for specsys, etc)
EPOCH  (EQUINOX is copied, but I don't know how it treats this deprecated option)

Then just looking at what is missing from the Apertif cubes:
ALTRVAL, ALTRPIX, TELESCOP, OBSERVER, OBSGEO-X, OBSGEO-Y, OBSGEO-Z, CELLSCAL

The second set of keywords may not be critical but might be good to follow the provenance of the data a little more--like telescope for example?  I guess including them inherently implies that we aren't trying to mosaic pointings from different telescopes using this tool.
