### ISSUE TITLE
Masked pixels become zero in mosaic, not NaN.

### ISSUE THREAD

**Issue by kmhess** [caracal-pipeline/MosaicQueen#19]
I'm mosaicking a pointing with a bunch of beams where the same channel is masked in all of them.  In the original cubes, these are masked, but in the mosaic all values are set to 0.  I think these should be NaNs so as not to be confused with pixels having real zero values (for example in source finding).
<img width="708" alt="Screen Shot 2022-03-22 at 10 27 42" src="https://user-images.githubusercontent.com/14857798/159449835-7aaca6dd-5c3c-4652-9650-59898a174f34.png">

**Comment by kmhess** [comment]
It might also be worth noting that the velocity that CARTA gives at the top of this screen shot is nonsense, but I believe that's because some of the header keywords are dropped in the mosaicking (restfreq, specsys, etc).  See #18.

**Comment by paoloserra** [comment]
Hey @kmhess . I can try to fix this but I'm not sure about what we want.

If a voxel at X,Y,Z of the mosaic is blanked in one input cube (after regridding) but not in the other input cubes, do we want to simply blank it in the mosaic or do we want to calculate its value using all non-blanked values?

The first approach is easy to implement but could be a bit of a waste.

The second approach might be trickier to implement (still possible) but might give a weird noise pattern, with sudden noise jumps. Take for example the case where a voxel is blanked in the input cube where it's closer to the beam centre, but not blanked in all other cubes where however it is close to the beam edge.

Let me know what you think and I can do some work to fix this.

**Comment by kmhess** [comment]
I would say calculate the pixel's value using all non-blanked values.

For my use case, it's entire channels that are blanked (one channel every
~64). In this case, I think if all the operations are done with the nan
prefix (like nansum, for example), then I believe doing something like
np.nansum(data*weights)/np.nansum(weights) will take care of the missing
data points appropriately.  In my case I'd rather not have the blanked
channels filled with zeros because if I want to do other operations on the
data--subtracting a spline fit for example--zero could become positive or
negative (and will be different pixel to pixel) and so that channel would
no longer be a reflection of the underlying data.  (For Apertif I spline
fit the data and then run SoFiA, so this would cause problems down the
line).  In my data all the same channels are blanked for all cubes.

It seems like it would be weird to have individual pixels in a cube
blanked, right?  Is there a use case where that would be useful?  I could
see the possibility of having adjacent pointings where a channel is blanked
in one pointing, but not the other...but in this case, if there's a lot of
overlap between the beams, one would want to use the useful data rather
than blanking anything that's missing, I think.  These issues would then be
reflected in the noise cube anyway, right?

**Comment by paoloserra** [comment]
@kmhess that should also work better now in the branch `estimate_noise` at #15 . Please test.

**Comment by kmhess** [comment]
In general it looks like the relative weighting works, the channels are
masked as I'd expect, and the header information is interpreted well by
CARTA.

So far the only change I've noticed is that the absolute values in
_noise.fits and _weights.fits are now different by about two orders of
magnitude to what they were previously.  I don't know if this matters or if
one is only worried about the relative values.  For example, previously the
values in the noise mosaic varied between 0-10 with a median of 2. Now they
vary between 0 to 0.04 (over a much more limit portion of the mosaic, but
still covering ~5 beams).  Previously the values in the weights cube varied
between 0.1 to ~1.5; now they vary between ~30 to ~850.  I'm not sure what
the _noise.fits and _weights.fits should be, but at least the absolute
values in the _image.fits are consistent between the before and after.

**Comment by paoloserra** [comment]
Hi @kmhess , I guess you're talking about current mosaicqueen master?

You're talking about a change in the noise and weights cubes, but can you clarify what you're comparing to? Master with ... ?

The current behaviour should be that the noise cube gives the actual rms noise level in the mosaic as a function of XY, in whatever units stated in the header. Older versions of mosaicqueen were producing a noise cube giving the error in units if the single-field rms (which was assumed to be the same for all fields), but that is no longer the case. I believe the new version is more useful.

Judging from https://github.com/caracal-pipeline/MosaicQueen/blob/a9e1951e2701fc0d5c3767664871fa7b4b9ac62a/mosaicqueen/make_mosaic.py#L649-L653 , `weights = 1/noise`

As you noticed, none of this should make a huge difference for the final mosaic. The only exception is the case where the noise varies significantly from field to field. In those cases, current master should do a much better job.
