### ISSUE TITLE
List of input images at command line

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/MosaicQueen#26]
Currently users must give input images at the command line as follows:

```
mosaic-queen -t <image1> -t <image2> ... -t <imageN>
```

This is because

https://github.com/caracal-pipeline/MosaicQueen/blob/34319d04d157c8dfae260ac50715b6fd4a4e4b18/mosaicQueen/main.py#L68-L70

I think it would friendlier to ask users to type:

```
mosaic-queen -t <image1> <image2> ... <imageN>
```

That should be possible with

```
 parser.add_argument("-t", "--target-images", nargs='+',
```

@SpheMakh do you agree, and would this be OK for when we later include this in Stimela?

**Comment by sphemakh** [comment]
Agreed.

**Comment by sphemakh** [comment]
@o-smirnov maybe we should switch to the scabha 2.0 parser? 

FYI @paoloserra: Then stimela would use the same parser which can also be used by caracal. So the new parameters, modifications would propagate automatically.

**Comment by paoloserra** [comment]
Your call -- let's just try not to blow up the list of depdendencies

**Comment by o-smirnov** [comment]
Sounds like a good mission for busy week?
