### ISSUE TITLE
mosaic queen failing because of a missing 'msg'

### ISSUE THREAD

**Issue by healytwin1** [caracal-pipeline/MosaicQueen#44]
I am running mosaic queen on ilifu using their singularity container, I am trying to mosaic a collection of continuum images from CARAcal using this command: `mosaic-queen -i /scratch3/projects/deb-a2626/CARACAL_run/mosaic/output/continuum -t aishani_a_Aishani_4-MFS-image.fits,jyoti_a_Jyoti_4-MFS-image.fits,nila_a_Nila_4-MFS-image.fits,aishani_b_Aishani_4-MFS-image.fits,jyoti_b_Jyoti_4-MFS-image.fits,nila_b_Nila_4-MFS-image.fits,kali_a_Kali_4-MFS-image.fits,shyama_a_Shyama_4-MFS-image.fits,kali_b_Kali_4-MFS-image.fits,shyama_b_Shyama_4-MFS-image.fits,bharati_a_Bharati_4-MFS-image.fits,matangi_a_Matangi_4-MFS-image.fits,tara_a_Tara_4-MFS-image.fits,bharati_b_Bharati_4-MFS-image.fits,matangi_b_Matangi_4-MFS-image.fits,tara_b_Tara_4-MFS-image.fits,bhairavi_a_Bhairavi_4-MFS-image.fits,bhairavi_b_Bhairavi_4-MFS-image.fits -o /scratch3/projects/deb-a2626/CARACAL_run/mosaic/output/mosaics/continuum -n cont_mosaic -r -j 8 -bc 0.2 -s mad -g 6.847041910836e-6`

but am getting this error:
```
2024-12-18 19:10:04,002 - MAKE_MOSAIC - INFO - Target images:
Traceback (most recent call last):
  File "/usr/local/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/mosaicqueen/main.py", line 149, in main
    naxis, nlongaxis = make_mosaic.find_naxis(input_dir, images)
  File "/usr/local/lib/python3.10/dist-packages/mosaicqueen/make_mosaic.py", line 485, in find_naxis
    log.error()
TypeError: Logger.error() missing 1 required positional argument: 'msg'
```

Any ideas on what I am doing wrong, or should be doing differently?

**Comment by paoloserra** [comment]
Before I look into this can you confirm that this is with the current master?

**Comment by healytwin1** [comment]
It is a good question, I am using whatever is in the `/idia/software/containers/mosaicqueen.sif` container. I've just installed the latest version from pypi on my laptop which failed with the same message. Having now installed it from the master branch, I actually get a sensible error message:
```
2024-12-18 17:41:08,089 - MAKE_MOSAIC - INFO - Target images:
2024-12-18 17:41:08,089 - MAKE_MOSAIC - ERROR - Inconsistent NAXIS in input files. fFund values []. Cannot proceed
Traceback (most recent call last):
  File "/Users/user/software/prabha/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/Users/user/software/prabha/lib/python3.8/site-packages/mosaicqueen/main.py", line 152, in main
    naxis, nlongaxis = make_mosaic.find_naxis(input_dir, images)
  File "/Users/user/software/prabha/lib/python3.8/site-packages/mosaicqueen/make_mosaic.py", line 598, in find_naxis
    raise ValueError(err_msg)
ValueError: Inconsistent NAXIS in input files. fFund values []. Cannot proceed
```
which I understand to be an issue with my input images

**Comment by paoloserra** [comment]
Yeah, we need a new stable release... But let's try to solve this from master for now.

One thing I've noticed is the comma-separated list of images. I normally use spaces. Does the log indicate that it's actually finding the input images? For simplicity you could try with just two images.

**Comment by healytwin1** [comment]
I had wondered if the target list should be comma separated or space - the instructions were not clear on that and I guess I default to comma separated.
Using spaces works - it is running on the ilifu version, failed on my laptop at the regrid stage with this error:
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
```

**Comment by healytwin1** [comment]
The ilifu version fails when it starts adding all the regrided images together: 
```
Traceback (most recent call last):
  File "/usr/local/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/mosaicqueen/main.py", line 249, in main
    noises = make_mosaic.make_mosaic_using_beam_info(input_dir, output_dir, mosaic_type, 'image', outname, imagesR, beamsR, beam_cutoff, unity_weights, statistic, sigma_guess, images, mosaic_cutoff, bitpix, naxis)
  File "/usr/local/lib/python3.10/dist-packages/mosaicqueen/make_mosaic.py", line 577, in make_mosaic_using_beam_info
    update_norm(norm_array, slc, beam_regrid_hdu, cutoff, ss)
  File "/usr/local/lib/python3.10/dist-packages/mosaicqueen/make_mosaic.py", line 439, in update_norm
    norm[slc] += tmp*mask
ValueError: operands could not be broadcast together with shapes (1,1,1210,1209) (1,1,1206,1202) (1,1,1210,1209) 
```
All of the input images are the same size and same projection, so I have no idea why some of the images are regridded to a difference size

**Comment by paoloserra** [comment]
The regridded images can have different sizes. That should not be the problem. Let me investigate, this rings a bell...

**Comment by paoloserra** [comment]
Can you please check whether the regridded primary beams have the same size as the corresponding regridded images?

The error you are getting seems to be the one described in #42 and fixed by #43 .

If that is the problem, you shouldn't be getting that error with master though ...

**Comment by paoloserra** [comment]
> the instructions were not clear

are you sure?? :)

The help is

```
-t TARGET_IMAGES [TARGET_IMAGES ...], --target-images TARGET_IMAGES [TARGET_IMAGES ...]
                      The filenames of each target/pointing image to be
                      mosaicked. A suffix of 'image.fits' is expected, and
                      this is replaced by 'pb.fits' in order to locate the
                      corresponding beams (which are also required as
                      input).
```

**Comment by healytwin1** [comment]
> > the instructions were not clear
> 
> are you sure?? :)
> 
> The help is
> 
> ```
> -t TARGET_IMAGES [TARGET_IMAGES ...], --target-images TARGET_IMAGES [TARGET_IMAGES ...]
>                       The filenames of each target/pointing image to be
>                       mosaicked. A suffix of 'image.fits' is expected, and
>                       this is replaced by 'pb.fits' in order to locate the
>                       corresponding beams (which are also required as
>                       input).
> ```

Correction: I probably did not understand the instructions...

**Comment by paoloserra** [comment]
BTW I've made an overdue release just now -- we'll see whether something else needs to be fixed!

**Comment by healytwin1** [comment]
> Can you please check whether the regridded primary beams have the same size as the corresponding regridded images?
> 
> The error you are getting seems to be the one described in #42 and fixed by #43 .
> 
> If that is the problem, you shouldn't be getting that error with master though ...

This probably is the issue.  I am going to ask ilifu to update so that I can test it properly as I am getting a python runtime error on my laptop that I don't understand when it tries to run montage

**Comment by paoloserra** [comment]
> failed on my laptop at the regrid stage with this error:

Are you requesting the right number of threads? Not sure we check that.

**Comment by healytwin1** [comment]
A good question, I have tried setting it to 4,8, the default, 1, all with the same outcome in that it fails. Leaving it to the default results in this error:
```
Traceback (most recent call last):
  File "/Users/user/software/mosaic/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/Users/user/software/mosaic/lib/python3.10/site-packages/mosaicqueen/main.py", line 230, in main
    make_mosaic.use_montage_for_regridding(
  File "/Users/user/software/mosaic/lib/python3.10/site-packages/mosaicqueen/make_mosaic.py", line 253, in use_montage_for_regridding
    ccc = future.result().split()[1].split('/')[-1]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

What is the optimal number of threads?

**Comment by paoloserra** [comment]
> What is the optimal number of threads?

My best answer is: as large as possible as long as you don't run out of memory.

And of course it should be at most equal to the number of threads on your machine.

**Comment by healytwin1** [comment]
Works now on ilifu - the previous patches have fixed the array size mismatch.
The version in CARACal needs to be updated as well since it still has the array size mismatch error.

**Comment by paoloserra** [comment]
Yes, CARACal uses an old MosaicQueen, but the update is not straightforward due to some changes in the way MosaicQueen works. It will be done eventually.
