### ISSUE TITLE
Mosaicking model.fits and residual.fits

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/MosaicQueen#8]
Currently we can mosaic the `image.fits` files only.

Including `model.fits` or `residual.fits` files in the input list of images to be mosaicked does not work because the input files are assumed to end with `image.fits`.

We could either lift  that assumption, and allow `model.fits` and `redisual.fits` files, too; or add a switch that, when mosaicking some `image.fits` files, allows one to also optionally mosaic the associated `model.fits` and `residual.fits` files.

**Comment by svw26** [comment]
Add switch for also mosaicking the model and residuals. Always mosaic the associated image x

**Comment by svw26** [comment]
Hiya @paoloserra, I'm confused by how many additional mosaics we want MosaicSteward to make, i.e. on top of the main 'image' one.

In #9 you say "It allowed me to coadd 24 x 18 GB cube (each with its 18 GB primary beam cube) and create a 77 GB mosaic cube and a 77 GB noise cube with 232 GB of available RAM." 

So does that mean we are to end up with: image, model, residual, noise, and weights? The last two are redundant, but that would still leave us with four mosaics, which would require even more memory... x

**Comment by paoloserra** [comment]
Since `noise` is the noise pattern in the mosaic cube or image, which is essential for accurate source finding, I don't think that it is redundant.

`weights` on the other hand is just `1/noise` (or `1/noise**2`, I don't remember) so I agree that it could  be dropped.

As for the memory requirement, `image`, `model` and `residual` could be mosaicked serially, so they.  do. not necessarily require more memory -- just more time.

Does that make sense to you?

**Comment by svw26** [comment]
Yep, I guess I should have said "reciprocal" rather than "redundant", and agree that ```noise``` would be the better one to keep. Ah, I see about the memory... Will stick to ```image```, ```model```, ```residual``` to start with, and come back to a ```noise``` mosaic once I've understood Josh's additions to the worker. Thanks x

**Comment by paoloserra** [comment]
There's something I don't understand -- `noise` is already made by the mosaic worker now. Are you removing it?

**Comment by svw26** [comment]
That's the thing *I* don't understand :P When I stopped working on CARACal the mosaic worker only generated primary beams where necessary. It never generated ```noise``` nor ```weights``` files, so I was puzzled by the output you'd posted (```The following mosaic FITS were written to disc: {0:s}.fits {0:s}_noise.fits {0:s}_weights.fits```). No, not removing it, if it's doing what we want already... x

**Comment by svw26** [comment]
Or maybe they were there, but my old log files didn't get that far :/ Can't remember now. x

**Comment by paoloserra** [comment]
Just to make sure we're on the same page, we're talking about a single `noise.fits` file per mosaic, not per input image. It's written by https://github.com/svw26/MosaicSteward/blob/e7cdb4f5dbb30af7cceeabb641691b5a086b40cc/MosaicSteward/make_mosaic.py#L186

**Comment by svw26** [comment]
Oh, thanks! That's where I'm getting confused. Yes, I have ```_weights.fits``` and ```_noise.fits``` being produced by previous runs, but not per input image. 

(And I'll need an estimate of the noise per input image so that I can resolve #5) x

**Comment by svw26** [comment]
Fixed via merging the 'multiple mosaics' branch x
